export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ROBOS_PENDING = 'REQUEST_ROBOS_PENDING';
export const REQUEST_ROBOS_SUCCESS = 'REQUEST_ROBOS_SUCCESS';
export const REQUEST_ROBOS_FAILURE = 'REQUEST_ROBOS_FAILURE';